### ISSUE TITLE
Cleanup code block tags

### ISSUE THREAD

**Issue by alexkazik** [orium/cargo-rdme#131]
Since the code blocks in the readme often do not compile anyway due to removing the comments, the extra tags are probably not helpful and can be removed/replaced.

Suggestion: when a code block is identified as rust (is_rust_code_block) then remove all tags and replace it with "rust".

Should probably optional or possible to switch off. Also someone may want to have another tag (including the empty string).

**Comment by orium** [comment]
It already does that.  It strips tags that only have meaning for `rustdoc`.  For instance if you have

````rust
//! ```should_panic
//! fail!("foo");
//! ```
````

cargo-rdme generates this README:

````markdown
```rust
fail!("foo");
```
````

This stuff is tested here: https://github.com/orium/cargo-rdme/blob/4191ebbec4587290317257933befb242c2d7d4f2/src/transform/rust_markdown_tag.rs#L321

If this is not what you mean, please give a concrete example.

**Comment by alexkazik** [comment]
Yes it does. I'm very sorry. For whatever reason I used "rust,no_compile" (and not ignore, I have no idea where I picked that up).

Interestingly enough the rust doc does what I want: do rust syntax highlight and not show a "untested" badge next to it (as ignore does).

**Comment by orium** [comment]
It seems `no_compile` is not currently a thing in rustdoc, but it seems it might become one: https://github.com/rust-lang/rust/pull/96573

When it does I'll update cargo-rdme to support that.
