### ISSUE TITLE
add ci integration example to readme

### ISSUE THREAD

**Issue by orhanbalci** [orium/cargo-rdme#141]
Hi there;
I was a cargo-sync-readme user but that project seems to be abandoned. Migrating my projects to cargo-rdme. It would be nice to have a github ci integration example on readme. I want to be able to have a PR if another PR have changes that updates README.

**Comment by orium** [comment]
Hi.

> I want to be able to have a PR if another PR have changes that updates README.

I'm not sure how easy that is, but I think it is a better idea to just fail CI of the original PR if it doesn't update the README.  I've added an example of github actions to the README.
