### ISSUE TITLE
Support intralinks for `impl` items such as methods

### ISSUE THREAD

**Issue by smoelius** [orium/cargo-rdme#166]
An intralink test involving a method does not seem to work for me.

Glancing here, the `SymbolType` for a method would appear to be `Fn`:
https://github.com/orium/cargo-rdme/blob/ca21a84ef9353f82767de8d1546200418a6c2ade/src/transform/intralinks/mod.rs#L261-L273

But when I try that by modifying one of the crate's existing tests, the generated URL doesn't appear to have the proper form.

Am I correct to infer that intralinks for methods are not yet supported?

**Comment by orium** [comment]
Yes, we never supported methods but since it is a common use case I started looking into it.  It's not just methods, I also want to implement support for `const` and `type` items inside `impl` blocks.

I should be able to implement it when I have a few hours this week.

**Comment by smoelius** [comment]
That would be great. Thank you. :pray:

**Comment by orium** [comment]
Opened #169 to cover other similar intralink limitations cases.

**Comment by smoelius** [comment]
Thanks very much for looking into this, @orium.

**Comment by orium** [comment]
Implemented in c278f705d8c1ebaab7687db17cfd01af5883356c.  Opened #170 to signal an annoying limitation.

**Comment by smoelius** [comment]
Thank you very much, @orium. For my use case, this works perfectly.
