### ISSUE TITLE
error: failed to get project info: project has no root package

### ISSUE THREAD

**Issue by smoelius** [orium/cargo-rdme#176]
Since the most recent release (1.4.1), I now see the above error when run here: https://github.com/trailofbits/dylint/tree/master/utils/testing

It worked fine with 1.4.0.

Any ideas?

**Comment by orium** [comment]
Yes, it was an issue introduced in 16f27910a1229414f6d20e8c50129014154f1f7b (see issue #175) and fixed in c9a5f03a036cc3ea7de7032fba58c1923c608964.

Version 1.4.2 fixes this.
