### ISSUE TITLE
Feature Inquiry - Add clap output

### ISSUE THREAD

**Issue by c-git** [orium/cargo-rdme#187]
This tool look really useful. I am inquiring if adding the clap help output to the readme has been considered as a feature. I want it for my use case so just asking if it's already been considered. Wasn't able to find anything in the issues.

1. Is this something that would be suitable to add to this tool?
2. If it is considered a desirable feature and I do get time to add it, is there anything I need to know before I create the PR other than what's in the contribution guidelines?

**Comment by orium** [comment]
Hi. I'm not entirely sure I want more than rustdoc in the `cargo-rdme`. I've though about it, and maybe one day I might decide to go that path, but not something I'm considering right now.

**Comment by c-git** [comment]
No problem, thanks for the feedback. If you decide to go down that path feel free to follow up with me as I will likely do it for my own use once I make some time.
