### ISSUE TITLE
`--intralinks-strip-links` not doing anything?

### ISSUE THREAD

**Issue by virtualritz** [orium/cargo-rdme#228]
Maybe I misunderstand the meaning of the CLI option.

I have this in my `lib.rs`

```
Use [`bar()`](Foo::bar) to baz.
```

With `--intralinks-strip-links` I would expect to get this in my `README.md`:

```
Use `bar()` to baz.
```

But I get:

```
Use [`bar()`](Foo::bar) to baz.
```

I.e. it seems the flag doesn't do anything?

**Comment by orium** [comment]
Currently `cargo-rdme` only supports links of the format `[⋯](crate::⋯)`, so those are currently not considered intralinks. If you write `[`bar()`](crate::Foo::bar)` it should work.

This is another limitation that will be removed once #177 is done.

**Comment by orium** [comment]
Closing as a dup of #151.
