### ISSUE TITLE
Linux binaries are missing in the latest release

### ISSUE THREAD

**Issue by orhun** [orium/cargo-rdme#239]
Hello!

I would like to integrate `cargo-rdme` to my CI via running the binary directly instead of installing via `cargo install`. However, I realized the MUSL binaries are missing from the latest release. Just wanted to ask if you are you planning to publish them 😊 

Thanks!

**Comment by orium** [comment]
It's an issue with rust-build.action (https://github.com/rust-build/rust-build.action/pull/99).

I'll generate the binaries manually later today and add them to the release.

**Comment by orium** [comment]
I've to look at the rust-build again: https://github.com/rust-build/rust-build.action/pull/99#issuecomment-2461002180

**Comment by orium** [comment]
Binary is published.
