### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by gifnksm** [orium/cargo-rdme#87]
`cargo-rdme --check` is useful for checking README in a CI environment.
However, pre-built binaries of cargo-rdme are not currently provided, and it takes a long time to build cargo-rdme in a CI environment.

Is it possible to provide pre-built binaries on the Release page of this repository?
If yes, I will create a pull request to add a GitHub Actions workflow.

**Comment by orium** [comment]
Hi.  I've just did a new release with pre-built binaries: https://github.com/orium/cargo-rdme/releases/tag/v0.7.1
